### ISSUE TITLE
[suggestion] Possibility to use assets

### ISSUE THREAD

**Issue by Fdom92** [ionic-team/stencil-dev-server#10]
Hi, i'm trying to use some svgs at assets folder but these folder its not being copied so the result is that the svgs are not found.

But if i copy the assets folder under the build path work as expected, so maybe just add a copy script from src/assets to build/assets?

I think this is quite useful but i let this on you.

Thanks!

**Comment by janpio** [comment]
Any reason you can't just put it in `build/assets` directly?

**Comment by Fdom92** [comment]
I can put it in build/assets yes but im asking if they can or have planned to add a 'copy' task on dev-server. 

If not ill just copy as you said :)

**Comment by jthoms1** [comment]
Sorry we would probably do this within the stencil build process not with the dev server.  I will move this issue over to the stencil core repo.

**Comment by jthoms1** [comment]
This issue was moved to ionic-team/stencil#138
