### ISSUE TITLE
Configuration: port setting?

### ISSUE THREAD

**Issue by jgw96** [ionic-team/stencil-dev-server#23]
_From @kristianmandrup on February 10, 2018 6:46_

Just tried to create a new app using the starter app, based on 0.4.0 release.

`npm start` Launches with port 333, but somehow I have an old StencilJS running on same port which is displayed instead! 

Is there a way to configure Stencil with the port to be used to host the http server?

Thanks.

In the meantime, I guess I need to shutdown my laptop to have the old instance terminated.

_Copied from original issue: ionic-team/stencil#514_

**Comment by jgw96** [comment]
Hey! Since this sounds like a dev-server related issue and not a stencil issue I am going to move this issue for now. Thanks!

**Comment by jgw96** [comment]
Hello @kristianmandrup . This can be caused by an errant service worker that you may have accidentally served on the same port that we use for dev. We are making some updates to fix this and you can expect those fixes soon. In the meantime you can do a hard refresh in your browser (`ctrl + r` on windows 10 using Chrome). Thanks!

**Comment by mlynch** [comment]
You can change the port by passing `--httpPort PORT` to `stencil-dev-server`
