### ISSUE TITLE
Customize opn browser

### ISSUE THREAD

**Issue by mattdsteele** [ionic-team/stencil-dev-server#24]
As noted in this Slack thread: https://stencil-worldwide.slack.com/archives/C7987GCA2/p1519464392000055

Allow customization of which browser gets opened. Done via `opn`: https://github.com/sindresorhus/opn#app

**Comment by jacktho** [comment]
Yes, I do not develop with my default browser.

**Comment by mattdsteele** [comment]
Probably don't need this here since Stencil's got an integrated dev server now.
