### ISSUE TITLE
Feature request: proxy configuration

### ISSUE THREAD

**Issue by neonguru** [ionic-team/stencil-dev-server#26]
Request that the stencil-dev-server supports proxying files from another server for given urls.
So it can be configured like this in stencil.config.js:

    exports.devServer = {
      root: 'www',
      watchGlob: '**/**',
      proxy: {
        'somefolder/someotherfolder': 'http://someserver'
      }
    }

**Comment by ardatan** [comment]
Any updates on this feature request?
