### ISSUE TITLE
Dev server shows last version (not latest) on livereload

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil-dev-server#3]
If I modify index.html, then save, the dev server will auto reload with the version before it. If I do a normal browser refresh, then I get the latest version (so, it's a version behind it seems)

**Comment by jthoms1** [comment]
I think I will need to add a cache busting mechanism.  Most likely just add an etag to all requests or I could just set everthing to max-age=0.

**Comment by jthoms1** [comment]
Version 0.0.13 has the no-cache headers that should prevent this from occurring.
