### ISSUE TITLE
Serve in "HTML5 mode"

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil-dev-server#4]
Many apps will want to let their router handle routing, so perhaps `npm run serve` should set up a local server in `www` with the root `index.html` page served on `/`, so the URL looks like

`http://localhost:3333/` not `http://localhost:3333/www/index.html`

**Comment by mlynch** [comment]
I messed something up

**Comment by jthoms1** [comment]
This can be set as the root during the configuration or through an option passed. Details for how to configure are now at the bottom of the readme.md file.
