### ISSUE TITLE
Use SSL by default

### ISSUE THREAD

**Issue by mlynch** [ionic-team/stencil-dev-server#6]
Browsers are moving to requiring SSL for a number of APIs so we should provide a self-signed cert and support this by default

**Comment by jthoms1** [comment]
I think in most cases there is an exception for localhost, but I agree we should include a cert and default to SSL.

**Comment by manucorporat** [comment]
I would say "self-signed cert" is almost the same as no security at all, ie http

**Comment by mlynch** [comment]
Security isn't the point for this, rather just enabling local dev server usage of web APIs. While there might be exclusions for localhost we can't guarantee they'll always be running under that domain

**Comment by relvao** [comment]
SSL as an option would be really useful. getUserMedia, for example, will not work without it.

**Comment by romulocintra** [comment]
Hi @mlynch i understand that this PR isn't a priority at all. Although this Issue wasn't assigned to me , if someone of you can test if Certificates run well in your machines, @relvao  @manucorporat @jthoms1 , and give me some revision on PR would be great , still WIP

**Comment by adamdbradley** [comment]
@romulocintra this is great! Yeah we'll test out the PR and it looks like it's using https://www.npmjs.com/package/devcert-san which seems well tested so this is awesome, thanks for doing this. There's one tasks left on the PR todo, should we wait on merging?

**Comment by romulocintra** [comment]
Hi @adamdbradley  left task is waiting for your inputs, code review and feedbacks , probably i should review a little bit code on test to avoid replication ... but i did not had time to review how to run same suite of test multiple times using different configurations ... 

Feel free to review and will change soons as possible based on your comments

**Comment by mhartington** [comment]
@romulocintra Thanks for the PR, could you shoot me an email, mike at ionic dot io. Have a few questions that I would love to ask

**Comment by romulocintra** [comment]
@mhartington  sent!! 👍

**Comment by jthoms1** [comment]
The PR has been merged. https://github.com/ionic-team/stencil-dev-server/pull/19
