### ISSUE TITLE
Dev-server caching files

### ISSUE THREAD

**Issue by Fdom92** [ionic-team/stencil-dev-server#7]
I was using stencil this days and i was getting a weird behaviour. 

**Problem:**
If i modify any tsx file, for example adding some html tags and then save, dev-server build again the app but the lastest changes wont be present.

**Version:**
dev-server version 0.0.13
stencil/core 0.0.4-6
stencil/utils 0.0.4

**Test:**
- Make changes in one tsx file
- Save the changes
- Clear navigation data, cache from the browser
- On dev tools go to aplication and clean cache, localstorage...
- Shut down the server and launch it again
- The latest changes are there now

**Comment by jthoms1** [comment]
Can you provide me with the OS you are running? This version should have the correct headers to disable cache.

If you could check the response headers for the HTML file from the dev-server and check that the response headers contain: "Cache-Control": "no-cache, no-store, must-revalidate, max-age=0"

**Comment by Fdom92** [comment]
On my personal laptop (Ubuntu 14.04.3 LTS) and version 0.0.13 seems like its working as expected, and the headers contain "Cache-Control:max-age=0".

So maybe on my other laptop i have the wrong version of dev-server, my fault :disappointed:

**Comment by jthoms1** [comment]
No worries,  Thanks for checking!
